name: flutter_application_134
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
   sdk: flutter
  
   


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.0.13  # shared_preferences: ^2.2.2 # for shared preferences
  flutter_iconly: ^1.0.2 # icons
  dio: ^5.4.1
  geolocator: ^7.6.2
  geocoding: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  
    
  flutter_lints: ^3.0.0
   
   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 uses-material-design: true
 assets:
     - images/splashback.png
     - images/loginback.png
     - images/rightarrow.png
     - images/tacologo.png
     - images/carton.png
     - images/cartoff.png
     - images/carton.png
     - images/menuoff.png
     - images/menuon.png
     - images/rewardon.png
     - images/rewardoff.png
     - images/accounton.png
     - images/accountoff.png
     - images/storeon.png
     - images/storeoff.png
    
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
